language: php

php:
  - 7.3
  - 7.4

env:
  - DB_CONNECTION=sqlite DB_DATABASE=':memory:'
  - DB_CONNECTION=mysql DB_DATABASE=migration_generator DB_HOST=127.0.0.1
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

services:
  - mysql

before_script:
  - mysql -e 'create database migration_generator'
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
