language: php

dist: precise

jobs:
  include:
    # ----------------- 7.2
    - name: "PHP 7.2 + SQLite"
      php: 7.2
      env: COMPOSER_FLAGS=""                DB_CONNECTION=sqlite DB_DATABASE=':memory:'
    - name: "PHP 7.2 + SQLite + lowest"
      php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=sqlite DB_DATABASE=':memory:'
    - name: "PHP 7.2 + MySQL"
      php: 7.2
      env: COMPOSER_FLAGS=""                DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE migration_generator'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.2 + MySQL + lowest"
      php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE migration_generator'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.2 + MariaDB"
      php: 7.2
      env: COMPOSER_FLAGS=""                DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mariadb
      addons:
        mariadb: "10.4"
      before_script:
        - sudo mysql -e 'CREATE DATABASE migration_generator'
        - sudo mysql -e 'GRANT all ON *.* to travis@localhost'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.2 + MariaDB + lowest"
      php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mariadb
      addons:
        mariadb: "10.4"
      before_script:
        - sudo mysql -e 'CREATE DATABASE migration_generator'
        - sudo mysql -e 'GRANT all ON *.* to travis@localhost'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    # ----------------- 7.3
    - name: "PHP 7.3 + SQLite"
      php: 7.3
      env: COMPOSER_FLAGS=""                DB_CONNECTION=sqlite DB_DATABASE=':memory:'
    - name: "PHP 7.3 + SQLite + lowest"
      php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=sqlite DB_DATABASE=':memory:'
    - name: "PHP 7.3 + MySQL"
      php: 7.3
      env: COMPOSER_FLAGS=""                DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE migration_generator'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.3 + MySQL + lowest"
      php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE migration_generator'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.3 + MariaDB"
      php: 7.3
      env: COMPOSER_FLAGS=""                DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mariadb
      addons:
        mariadb: "10.4"
      before_script:
        - sudo mysql -e 'CREATE DATABASE migration_generator'
        - sudo mysql -e 'GRANT all ON *.* to travis@localhost'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.3 + MariaDB + lowest"
      php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mariadb
      addons:
        mariadb: "10.4"
      before_script:
        - sudo mysql -e 'CREATE DATABASE migration_generator'
        - sudo mysql -e 'GRANT all ON *.* to travis@localhost'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    # ----------------- 7.4
    - name: "PHP 7.4 + SQLite"
      php: 7.4
      env: COMPOSER_FLAGS=""                DB_CONNECTION=sqlite DB_DATABASE=':memory:'
    - name: "PHP 7.4 + SQLite + lowest"
      php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=sqlite DB_DATABASE=':memory:'
    - name: "PHP 7.4 + MySQL"
      php: 7.4
      env: COMPOSER_FLAGS=""                DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE migration_generator'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.4 + MySQL + lowest"
      php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE migration_generator'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.4 + MariaDB"
      php: 7.4
      env: COMPOSER_FLAGS=""                DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mariadb
      addons:
        mariadb: "10.4"
      before_script:
        - sudo mysql -e 'CREATE DATABASE migration_generator'
        - sudo mysql -e 'GRANT all ON *.* to travis@localhost'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - name: "PHP 7.4 + MariaDB + lowest"
      php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql  DB_DATABASE=migration_generator DB_HOST=127.0.0.1 DB_USERNAME=travis
      services:
        - mariadb
      addons:
        mariadb: "10.4"
      before_script:
        - sudo mysql -e 'CREATE DATABASE migration_generator'
        - sudo mysql -e 'GRANT all ON *.* to travis@localhost'
        - travis_retry composer self-update
        - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
