name: Tests MariaDB

on: [push, pull_request]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        composer-dependency: [prefer-stable, prefer-lowest]

    name: "MariaDB - PHP ${{ matrix.php }} - ${{ matrix.composer-dependency }}"

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_DATABASE: migration_generator
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --${{ matrix.composer-dependency }}

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: mysql
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_DATABASE: migration_generator
          DB_USERNAME: root
          DB_PASSWORD: test
