name: Tests MySQL

on:

  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        composer-dependency: [prefer-stable, prefer-lowest]

    name: "MySQL - PHP ${{ matrix.php }} - ${{ matrix.composer-dependency }}"

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: migration_generator
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --${{ matrix.composer-dependency }}

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: mysql
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_DATABASE: migration_generator
          DB_USERNAME: root
          DB_PASSWORD: test
